name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: django-project-465420
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/django-project-465420/django-repo/django-app:latest .
        docker push us-central1-docker.pkg.dev/django-project-465420/django-repo/django-app:latest

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials django-cluster --zone us-central1-a
        kubectl apply -f k8s
